const First_name = 'Jwan';
const Last_name = 'Ali';
const Age = 40;
const DateOfBirth =  '10/01/1979';
const Address = '818-220 Oakland ave';
console.log('firstName: ',First_name);
console.log('lastName: ', Last_name);
console.log('Age: ',Age);
console.log('Dat Of Birh: ',DateOfBirth);
console.log('Address: ',Address);