let text = 'HELLO';
let result ;
let textLength = text.length;
result = text.charAt(textLength-1);
--textLength;
result =result.concat(text.charAt(textLength-1));
--textLength;
result =result.concat(text.charAt(textLength-1));
--textLength;
result =result.concat(text.charAt(textLength-1));
--textLength;
result =result.concat(text.charAt(textLength-1));
--textLength;
result =result.concat(text.charAt(textLength-1));
--textLength;
result =result.concat(text.charAt(textLength-1));
--textLength;
result = result.toLowerCase();
console.log(`The final result is : ${result}`);
result = result.toUpperCase();
console.log(`The final result in upperCase is : ${result}`);
console.log(`final result's length is : ${result.length}, and the orginal text lenth is : ${text.length}`);