var First_name = 'Jwan';
var Last_name = 'Ali';
var Age = 40;
var DateOfBirth =  '10/01/1979';
var Address = '818-220 Oakland ave';
console.log(First_name);
console.log(Last_name);
console.log(Age);
console.log(DateOfBirth);
console.log(Address);