let iceCreamFlavors = [];
iceCreamFlavors.unshift('orange');
iceCreamFlavors.unshift('apple');
iceCreamFlavors.unshift('black berry');
iceCreamFlavors.unshift('mint');
iceCreamFlavors.unshift('blue moon');
iceCreamFlavors.unshift('cherry');
iceCreamFlavors.unshift('chocolate');
iceCreamFlavors.unshift('cookies and cream');
iceCreamFlavors.unshift('french vanilla');
iceCreamFlavors.unshift('banana');
console.log(iceCreamFlavors);