var First_name = 'Jwan';
var Last_name = 'Ali';
var Age = 40;
var DateOfBirth =  '10/01/1979';
var Address = '818-220 Oakland ave';
console.log('firstName: ',First_name);
console.log('lastName: ', Last_name);
console.log('Age: ',Age);
console.log('Dat Of Birh: ',DateOfBirth);
console.log('Address: ',Address);