let First_name = 'Jwan';
let Last_name = 'Ali';
let Age = 40;
let DateOfBirth =  '10/01/1979';
let Address = '818-220 Oakland ave';
console.log('firstName: ',First_name);
console.log('lastName: ', Last_name);
console.log('Age: ',Age);
console.log('Dat Of Birh: ',DateOfBirth);
console.log('Address: ',Address);