let NameOfCity = 'Winnipeg';
let province = 'Manitoba';
let country = 'Canada';
let mayor = 'Brian Bowman';
let population = 753700;
let hasSea = false;
let hasLake = true;
let hasRiver = true;
let numberOfRiver = null;
let WinnipegBorder = undefined;
let WinnipegArea = 464.08 ;
let WinnipegAreaType = 'km^2';
let dateOfEstablishment = 1738;
console.log('Name Of City:           ',NameOfCity);
console.log('province:               ',province);
console.log('country:                ',country);
console.log('mayor:                  ',mayor);
console.log('population:             ',population);
console.log('has a sea:              ',hasSea);
console.log('has a lake:             ',hasLake);
console.log('has a river:            ',hasRiver);
console.log('number of river:        ',numberOfRiver);
console.log("Winnipeg's Border:      ",WinnipegBorder);
console.log('winnipeg area:          ',WinnipegArea,WinnipegAreaType);
console.log('date of Establishment:  ',dateOfEstablishment);
console.log('Name Of City:         //',typeof NameOfCity);
console.log('province:             //',typeof province);
console.log('country:              //',typeof country);
console.log('mayor:                //',typeof mayor);
console.log('population:           //',typeof population);
console.log('has a sea:            //',typeof hasSea);
console.log('has a lake:           //',typeof hasLake);
console.log('has a river:          //',typeof hasRiver);
console.log('number of river:      //',typeof numberOfRiver);
console.log("Winnipeg's Border:    //",typeof WinnipegBorder);
console.log('winnipeg area:        //',typeof WinnipegArea,WinnipegAreaType);
console.log('date of Establishment://',typeof dateOfEstablishment);